version: "3"
services:

  api:
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app

  cient:
    build: ./client
    ports:
      - '5000:80'
    volumes:
      - ./client:/usr/share/nginx/html
